todo_application/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('todos/', include('todos.urls')),
    path('admin/', admin.site.urls),
]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('addTodo/', views.addTodo, name='addTodo'),
    path('addCategory/', views.addCategory, name='addCategory'),
    path('<int:todo_id>/edit/', views.edit, name='edit'),
    path('<int:todo_id>/update/', views.update, name='update'),
    path('<int:todo_id>/delete/', views.delete, name='delete'),
]

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Todo, Category, NotificationTime
import dateutil.parser as parser
from django.core.mail import send_mail
from django.http import HttpResponse
from datetime import datetime, time
import sqlite3
import time, traceback
import threading


def index(request):
    todo_items = Todo.objects.order_by('-due_date')[:10]
    category_items = Category.objects.all()
    notification_time = NotificationTime.objects.all()

    current_date_time = datetime.now()
    dt_string = current_date_time.strftime("%m/%d/%Y %I:%M %p")
    splited_dt_string = dt_string.split(" ")

    context = {
        'todo_items': todo_items,
        'category_items': category_items,
        'notification_time' : notification_time,
        'hide_side_bar' : False,
        'current_date': splited_dt_string[0] + str().join(" ") + splited_dt_string[1] + str().join(" ") + splited_dt_string[2]
    }
    return render(request, 'todos/index.html', context)


def addTodo(request):
    receiver_email = ""
    notification_time = "not available"
    if request.POST['email_notification']:
        receiver_email = request.POST['email_notification']

    if request.POST['todo_notification_time']:
        notification_time = request.POST['todo_notification_time']

    sendEmail(request, receiver_email, notification_time)

    new_item = Todo(todo_text = request.POST['todo_text'],
                    date_created = (parser.parse(request.POST['date_created'])).isoformat(),
                    due_date = (parser.parse(request.POST['due_date'])).isoformat(),
                    category_id = request.POST['todo_category'],
                    email_notification = request.POST['email_notification'],
                    notification_time = notification_time)

    new_item.save()
    category_id = request.POST['todo_category']
    category = get_object_or_404(Category, pk=category_id)
    category.todo_count += 1
    category.save()
    return redirect("/todos")


def addCategory(request):
    new_category = Category(category_name = request.POST['category_name'])
    new_category.save()
    return redirect("/todos")


def edit(request, todo_id):
    if request.path == "/todos/" + str(todo_id) + "/edit/":
        hide_side_bar = True

    todo = get_object_or_404(Todo, pk=todo_id)
    due_date = todo.due_date.strftime("%m/%d/%Y %I:%M %p")
    splited_due_date_string = due_date.split(" ")

    context = {
        'todo_id' : todo_id,
        'todo_text' : todo.todo_text,
        'due_date': splited_due_date_string[0] + str().join(" ") + splited_due_date_string[1] + str().join(" ") + splited_due_date_string[2],
        'hideSideBar' : hide_side_bar
    }
    return render(request, 'todos/edit.html', context)


def update(request, todo_id):

    edited_item = request.POST['todo_text']
    edited_due_date = (parser.parse(request.POST['due_date'])).isoformat()
    todo = get_object_or_404(Todo, pk=todo_id)
    todo.todo_text = edited_item
    todo.due_date = edited_due_date
    todo.save()

    return redirect("/todos")


def delete(request, todo_id):
    todo = get_object_or_404(Todo, pk=todo_id)
    Todo.delete(todo)

    category = get_object_or_404(Category, pk= todo.category_id)
    category.todo_count -= 1
    category.save()
    return redirect("/todos")


def sendEmail(request, receiver_email, notification_time):

    email_body = """
    You have added a new todo_item.
    You can edit and delete the todo_item anytime.
    Your item will expire in """ + str(notification_time) + "!"

    send_mail(
        'Todo_Notification',
        email_body,
        'noreply@todo_application.ca',
        [receiver_email],
        fail_silently=False,
    )
    return HttpResponse('Mail successfully sent')


def check_time(delay, task):
  next_time = time.time() + delay
  while True:
    time.sleep(max(0, next_time - time.time()))
    try:
      task()
    except Exception:
      traceback.print_exc()
    # skip tasks if we are behind schedule:
    next_time += (time.time() - next_time) // delay * delay + delay

def is_expired():
    connection = sqlite3.connect('db.sqlite3')
    cursor = connection.cursor()
    cursor.execute(" SELECT * FROM todos_todo where email_notification != '' AND notification_time != 'None' AND sent_reminder == 'False' ")
    rows = cursor.fetchall()
    todo_notify_time = 0

    for row in rows:
        todo_item_id = row[0]
        due_date_in_ms = int(datetime.fromisoformat(row[3]).timestamp() * 1000)
        current_date = int(datetime.now().timestamp() * 1000)
        splited_notification_time = str(row[6]).split(" ")
        receiver_email = row[5]
        sent_reminder = row[7]
        date_in_pst = due_date_in_ms - (7 * 60 * 60 * 1000)
        time_remaining = date_in_pst - current_date

        if splited_notification_time[0] != "None":
            if splited_notification_time[1] == "minutes":
                todo_notify_time = int((splited_notification_time[0])) * 60 * 1000
            elif splited_notification_time[1] == "hours":
                todo_notify_time = int((splited_notification_time[0])) * 60 * 60 * 1000
            elif splited_notification_time[1] == "day":
                todo_notify_time = int((splited_notification_time[0])) * 60 * 60 * 24 * 1000

        if time_remaining <= todo_notify_time:
            todo_item_expire = "Your todo_item name - " + str(row[1]) +  " will expire in " + str(row[6]) + "! "

            send_mail(
                'Todo_Notification',
                todo_item_expire,
                'noreply@todo_application.ca',
                [receiver_email],
                fail_silently=False,
            )

            selected_todo_item = get_object_or_404(Todo, pk=int(todo_item_id))
            selected_todo_item.sent_reminder = "True"
            selected_todo_item.save()

threading.Thread(target=lambda: check_time(1, is_expired)).start()

todos/templates/todos/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Bootstrap 4 -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
<!--    <link rel="stylesheet" href="../../static/todos/sidebar.css">-->
<!--    <link rel="stylesheet" href="../../static/todos/edit_dialog.css">-->
    <link rel="stylesheet" href="https://todo-app-python-django.scm.azurewebsites.net/wwwroot/todos/static/todos/sidebar.css">
    <link rel="stylesheet" href="https://todo-app-python-django.scm.azurewebsites.net/wwwroot/todos/static/todos/edit_dialog.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

    <title>Todo App</title>
  </head>
  <body>

  {% if hide_side_bar == False %}
    <div class="sidebar">
      <a class="active" href="#home">
        <i class="fa fa-user"></i>
        <span class="home">Home</span>
      </a>
      {% for category in category_items %}
        <a href="#category" class="category_list" data-toggle="modal" data-target=#{{category.category_name}}>
          {% if category.category_name == "Personal" %}
            <i class="fa fa-home"></i>
          {% elif category.category_name == "Office" %}
            <i class="fa fa-laptop"></i>
          {% elif category.category_name == "Travel" %}
            <i class="fa fa-plane"></i>
          {% else %}
            <i class="fa fa-list-ul"></i>
          {% endif %}
          <span class="category_name">{{category.category_name}}</span>
          <span class="todo_count">{{category.todo_count}}</span>
        </a>
      {% endfor %}
      <div class="addTaskButton">
        <a href="#" data-toggle="modal" data-target="#myModal">
          <i class="fa fa-plus"></i>
          <span class="addTask">Add Task</span>
        </a>
      </div>
      <div class="addTaskButton">
        <a href="#" data-toggle="modal" data-target="#category_Modal">
          <i class="fa fa-plus"></i>
          <span class="addCategory">Add Category</span>
        </a>
      </div>
    </div>
  {% endif %}

  <script>
    var active_timer;
    function timer_interval(todo_id, due_date) {
      active_timer = setInterval(function() {
        timer(todo_id, due_date);
      }, 1000);
    }

    function timer(todo_id, due_date){

      var countDownDate = new Date(due_date).getTime();
      var now = new Date().getTime();
      var distance = countDownDate - now;

      // Time calculations for days, hours, minutes and seconds
      var days = Math.floor(distance / (1000 * 60 * 60 * 24));
      var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((distance % (1000 * 60)) / 1000);

      $(".todo_item" + todo_id).html("Time Remaining : " + days + "d " + hours + "h " + minutes + "m " + seconds + "s ");
      $(".todo_item" + todo_id).css("color", "green");

      if (distance < 0) {
        clearInterval(active_timer);
        $(".todo_item" + todo_id).html("");
      }
    }

  </script>

  {% block content %}
  {% endblock %}

  <script>
    $(function () {
      $("#dateCreated").datetimepicker();
      $("#dueDate").datetimepicker();
    });
  </script>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todos/templates/todos/edit.html
{% extends 'todos/base.html' %}
{% load static %}

{% block content %}
  <link rel="stylesheet" type="text/css" href="{% static 'todos/edit_dialog.css' %}">
  <div class="dialog_container">
    <!-- The Modal -->
    <div class="dialog" id="edit_todo_dialog">
      <!-- Modal Header -->
      <div class="dialog_header">
        <h4 class="dialog_title">Edit Todo_Item</h4>
      </div>

      <!-- Modal body -->
      <div class="dialog-body">
        <div class="todo_edit_form">
          <form action="{% url 'todos:update' todo_id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <input type="text" class="form-control" name="todo_text" value="{{todo_text}}">
              <div class="input-group date" id="dateCreated" data-target-input="nearest" style="top: 1em;">
                <input type="text" class="form-control datetimepicker-input"  name ="due_date" value="{{due_date}}" data-target="#dateCreated"/>
                <div class="input-group-append" data-target="#dateCreated" data-toggle="datetimepicker">
                  <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                </div>
              </div>
            </div>
            <div class="dialog_footer">
              <button type="submit" class="btn btn-primary">Save & Close</button>
              <button type="submit" class="btn btn-danger"><a href="/todos">Close</a></button>
            </div>
          </form>
        </div>
      </div>
    </div>
    </div>
{% endblock %}

todos/templates/todos/index.html
{% extends 'todos/base.html' %}
{% load static %}
{% block content %}

  <link rel="stylesheet" type="text/css" href="{% static 'todos/style.css' %}">

  <h2 class="applicationHeader">TODO APPLICATION</h2>
  <hr>

  <div class="todoItems">
    {% if todo_items %}
      <ul>
        {% for todo in todo_items %}
        <li class="todoList">
          <div class="todoText">
            <input type="radio", name="selectedItem", id="selectedItem" style="margin-right:1em;">
            <p style="display: inline-block;">{{todo.todo_text}}</p>
            <p><i class="fa fa-calendar"></i>{{todo.due_date}}</p>
            <script>
             timer_interval("{{todo.id}}" , "{{ todo.due_date|date:"M d, Y H:i:s" }}");
            </script>
            <p style="text-align: center" class="todo_item{{todo.id}}"></p>
          </div>
          <div class="editAndDeleteButton">
            <button class="btn btn-primary"><a href="{% url 'todos:edit' todo.id %}"><i class="fa fa-edit"></i></a></button>
            <button class="btn btn-primary"><a href="{% url 'todos:delete' todo.id %}"><i class="fa fa-trash"></i></a></button>
          </div>
        </li>
        {% endfor %}
      </ul>
    {% endif %}
  </div>

  <div class="container">
    <!-- The Modal -->
    <div class="modal" id="myModal">
      <div class="modal-dialog">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title">Add New Task</h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">
            <div class="todoForm">
              <form action="{% url 'todos:addTodo' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="addTodo">What do you want to add?</label>
                  <input type="text" class="form-control" id="addTodo"  name="todo_text" placeholder="Description">
                </div>
                <div class="form-group" style="margin-top: 1em;">
                  <label for="addTodo">Would you like to get email notification?(Optional)</label>
                  <input type="email" class="form-control" id="email_notification"  name="email_notification" placeholder="example@example.com">
                </div>
                <div class="form-group">
                  <label>Choose a notification time : </label>
                  <select style="width: 30%;" name="todo_notification_time">
                   {% for interval in notification_time %}
                    <option value="{{interval.notification_time}}">{{interval.notification_time}}</option>
                   {% endfor %}
                  </select>
                </div>
                <div class="form-group">
                  <label>Select a category : </label>
                  <select style="width: 30%;" name="todo_category">
                   {% for category in category_items %}
                    <option value={{category.id}}>{{category.category_name}}</option>
                   {% endfor %}
                  </select>
                </div>
                <div class="dateField">
                  <div class="input-group date" id="dateCreated" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input"  name ="date_created" value="{{current_date}}" placeholder="Date created" data-target="#dateCreated"/>
                    <div class="input-group-append" data-target="#dateCreated" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                  </div>
                  <div class="input-group date" id="dueDate" data-target-input="nearest">
                    <input type="text" class="form-control datetimepicker-input"  name ="due_date" placeholder="Due date" data-target="#dueDate"/>
                    <div class="input-group-append" data-target="#dueDate" data-toggle="datetimepicker">
                      <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-primary">Add</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
      <!-- The Modal -->
      <div class="modal" id="category_Modal">
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Create Category</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              <div class="categoryForm">
                <form action="{% url 'todos:addCategory' %}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                    <label for="addTodo">Which category do you want to add?</label>
                    <input type="text" class="form-control" id="addCategory"  name="category_name" placeholder="Description">
                  </div>
                  <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Add</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  <div class="container">
      <!-- The Modal -->
    {% for category in category_items %}
      <div class="modal" id={{category.category_name}}>
        <div class="modal-dialog">
          <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
              <h4 class="modal-title">Items In {{category.category_name}} Category</h4>
              <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
              {% for todo in todo_items %}
                {% if todo.category_id  == category.id %}
                  <p>{{todo.todo_text}}</p>
                {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    </div>
{% endblock %}